# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Traveller' do

pod 'RAMAnimatedTabBarController'
pod 'LTNavigationBar'
pod 'SnapKit'
pod 'SDCycleScrollView','~> 1.64'
pod 'MJRefresh'
pod 'UITableView+FDTemplateLayoutCell'
#pod 'Alamofire', '3.4'
#pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
#pod 'PKHUD'
#pod 'SDWebImage'

end

target 'TravellerTests' do

end

